config/routes.rb
	GerenciadorProjetos::Application.routes.draw do
  resources :projetos

  resources :tipos_projetos

  resources :statuses

end

app/models/projeto.rb
class Projeto < ActiveRecord::Base
has_many :projetos

validates_presence_of :status, :message => " - deve ser preenchido"
validates_presence_of :tipo_projeto, :message => " - deve ser preenchido"

end

app/models/status.rb
class Status < ActiveRecord::Base
belongs_to :projetos
end

app/models/tipos_projeto.rb
class TiposProjeto < ActiveRecord::Base
belongs_to :projetos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = Projeto.all
#@projetos.status = Status.find(@projetos.status)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projetos }
    end
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
    @projeto = Projeto.find(params[:id])
    @projeto.status = Status.find(@projeto.status)
    @projeto.tipo_projeto = TiposProjeto.find(@projeto.tipo_projeto)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @projeto }
    end
  end	

  # GET /projetos/new
  # GET /projetos/new.json
  def new
    @projeto = Projeto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @projeto }
    end
  end

  # GET /projetos/1/edit
  def edit
    @projeto = Projeto.find(params[:id])
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(params[:projeto])

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto was successfully created.' }
        format.json { render json: @projeto, status: :created, location: @projeto }
      else
        format.html { render action: "new" }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projetos/1
  # PUT /projetos/1.json
  def update
    @projeto = Projeto.find(params[:id])

    respond_to do |format|
      if @projeto.update_attributes(params[:projeto])
        format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto = Projeto.find(params[:id])
    @projeto.destroy

    respond_to do |format|
      format.html { redirect_to projetos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tipos_projetos_controller.rb
class TiposProjetosController < ApplicationController
  # GET /tipos_projetos
  # GET /tipos_projetos.json
  def index
    @tipos_projetos = TiposProjeto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipos_projetos }
    end
  end

  # GET /tipos_projetos/1
  # GET /tipos_projetos/1.json
  def show
    @tipos_projeto = TiposProjeto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipos_projeto }
    end
  end

  # GET /tipos_projetos/new
  # GET /tipos_projetos/new.json
  def new
    @tipos_projeto = TiposProjeto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipos_projeto }
    end
  end

  # GET /tipos_projetos/1/edit
  def edit
    @tipos_projeto = TiposProjeto.find(params[:id])
  end

  # POST /tipos_projetos
  # POST /tipos_projetos.json
  def create
    @tipos_projeto = TiposProjeto.new(params[:tipos_projeto])

    respond_to do |format|
      if @tipos_projeto.save
        format.html { redirect_to @tipos_projeto, notice: 'Tipos projeto was successfully created.' }
        format.json { render json: @tipos_projeto, status: :created, location: @tipos_projeto }
      else
        format.html { render action: "new" }
        format.json { render json: @tipos_projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipos_projetos/1
  # PUT /tipos_projetos/1.json
  def update
    @tipos_projeto = TiposProjeto.find(params[:id])

    respond_to do |format|
      if @tipos_projeto.update_attributes(params[:tipos_projeto])
        format.html { redirect_to @tipos_projeto, notice: 'Tipos projeto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipos_projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos_projetos/1
  # DELETE /tipos_projetos/1.json
  def destroy
    @tipos_projeto = TiposProjeto.find(params[:id])
    @tipos_projeto.destroy

    respond_to do |format|
      format.html { redirect_to tipos_projetos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def menu_principal
		menu = %w(projeto status tipos_projeto)
		menu_principal = "<ul>"
		menu.each do |item|
		menu_principal << "<li>" + link_to(item, :controller => item.pluralize) + "</li>"
	end
		menu_principal << "</ul>"
		raw menu_principal
	end

end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tipos_projetos_helper.rb
module TiposProjetosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GerenciadorProjetos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= menu_principal %>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>

app/views/projetos/_form.html.erb
<%= form_for(@projeto) do |f| %>
  <% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "error") %> Proibe o projeto de ser salvo:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
    <div class="field">
    <%= f.label :responsavel %><br />
    <%= f.text_field :responsavel %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :tipos_projeto %><br />
	<%= collection_select(:projeto, :tipo_projeto, TiposProjeto.all, :id, :tipo, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :valor_do_contrato %><br />
    <%= f.text_field :valor_do_contrato %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
	<%= collection_select(:projeto, :status, Status.all, :id, :descricao, :prompt => true) %>	
	
	
    
  </div>
  <div class="field">
    <%= f.label :justificativa_do_status %><br />
    <%= f.text_field :justificativa_do_status %>
  </div>
  <div class="field">
    <%= f.label :inicio %><br />
    <%= f.date_select :inicio %>
  </div>
  <div class="field">
    <%= f.label :termino %><br />
    <%= f.date_select :termino %>
  </div>
  <div class="field">
    <%= f.label :colaboradores %><br />
    <%= f.text_field :colaboradores %>
  </div>
  <div class="field">
    <%= f.label :anexos %><br />
    <%= f.text_field :anexos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projetos/edit.html.erb
<h1>Editando Projeto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @projeto %> |
<%= link_to 'Voltar', projetos_path %>

app/views/projetos/index.html.erb
<h1>Gerenciamento de Projetos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descri&ccedil&atildeo</th>
    <th>Tipo projeto</th>
    <th>Valor do contrato</th>
    <th>Status</th>
    <th>Justificativa do status</th>
    <th>In&iacutecio</th>
    <th>T&eacutermino</th>
    <th>Colaboradores</th>
    <th>Anexos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projetos.each do |projeto| %>
  <tr>

    <td><%= projeto.nome %></td>
    <td><%= projeto.descricao %></td>
    <td><%= TiposProjeto.find(projeto.tipo_projeto).tipo %></td>
    <td><%= projeto.valor_do_contrato %></td>
    <td><%= Status.find(projeto.status).descricao%></td>
    <td><%= projeto.justificativa_do_status %></td>
    <td><%= projeto.inicio %></td>
    <td><%= projeto.termino %></td>
    <td><%= projeto.colaboradores %></td>
    <td><%= projeto.anexos %></td>
    <td><%= link_to 'Mostrar', projeto %></td>
    <td><%= link_to 'Editar', edit_projeto_path(projeto) %></td>
    <td><%= link_to 'Excluir', projeto, confirm: 'Tem certeza que deseja excluir o projeto?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Projeto', new_projeto_path %>

app/views/projetos/new.html.erb
<h1>Novo projeto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', projetos_path %>

app/views/projetos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @projeto.nome %>
</p>

<p>
  <b>Descri&ccedil&atildeo:</b>
  <%= @projeto.descricao %>
</p>

<p>
  <b>Tipo do projeto:</b>
  <%= @projeto.tipo_projeto.tipo %>
</p>

<p>
  <b>Valor do contrato:</b>
  <%= @projeto.valor_do_contrato %>
</p>

<p>
  <b>Status:</b>
  <%= @projeto.status.descricao %>
</p>

<p>
  <b>Justificativa do status:</b>
  <%= @projeto.justificativa_do_status %>
</p>

<p>
  <b>In&iacutecio:</b>
  <%= @projeto.inicio %>
</p>

<p>
  <b>T&eacutermino:</b>
  <%= @projeto.termino %>
</p>

<p>
  <b>Colaboradores:</b>
  <%= @projeto.colaboradores %>
</p>

<p>
  <b>Anexos:</b>
  <%= @projeto.anexos %>
</p>


<%= link_to 'Editar', edit_projeto_path(@projeto) %> |
<%= link_to 'Voltar', projetos_path %>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> Proibe o projeto de ser salvo:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editando status</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @status %> |
<%= link_to 'Voltar', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listando Status</h1>

<table>
  <tr>
    <th>Descri&ccedil&atildeo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  <tr>
    <td><%= status.descricao %></td>
    <td><%= link_to 'Mostrar', status %></td>
    <td><%= link_to 'Editar', edit_status_path(status) %></td>
    <td><%= link_to 'Excluir', status, confirm: 'Tem certeza que deseja excluir o status?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>Novo status</h1>

<%= render 'form' %>

<%= link_to 'Voltar', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descri&acedil&atildeo:</b>
  <%= @status.descricao %>
</p>


<%= link_to 'Editar', edit_status_path(@status) %> |
<%= link_to 'Voltar', statuses_path %>

app/views/tipos_projetos/_form.html.erb
<%= form_for(@tipos_projeto) do |f| %>
  <% if @tipos_projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipos_projeto.errors.count, "error") %> Proibe o projeto de ser salvo:</h2>

      <ul>
      <% @tipos_projeto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos_projetos/edit.html.erb
<h1>Editando tipos_projeto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @tipos_projeto %> |
<%= link_to 'Voltar', tipos_projetos_path %>

app/views/tipos_projetos/index.html.erb
<h1>Listando Tipos de Projetos</h1>

<table>
  <tr>
    <th>Tipo</th>
    <th>Descri&ccedil&atildeo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tipos_projetos.each do |tipos_projeto| %>
  <tr>
    <td><%= tipos_projeto.tipo %></td>
    <td><%= tipos_projeto.descricao %></td>
    <td><%= link_to 'Show', tipos_projeto %></td>
    <td><%= link_to 'Edit', edit_tipos_projeto_path(tipos_projeto) %></td>
    <td><%= link_to 'Destroy', tipos_projeto, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Tipo de Projeto', new_tipos_projeto_path %>

app/views/tipos_projetos/new.html.erb
<h1>Novo Tipo de Projeto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', tipos_projetos_path %>

app/views/tipos_projetos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo:</b>
  <%= @tipos_projeto.tipo %>
</p>

<p>
  <b>Descri&ccedil&atildeo:</b>
  <%= @tipos_projeto.descricao %>
</p>


<%= link_to 'Editar', edit_tipos_projeto_path(@tipos_projeto) %> |
<%= link_to 'Voltar', tipos_projetos_path %>